import { useCallback, useEffect, useState } from 'react';
import { Archive, Copy, ExternalLink, FolderPlus, KeyRound, Plus } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import DashLayout from '../components/DashLayout';
import { DetailPage, DetailSection, ErrorDetail, LoadingDetail, formatDate, humanize } from '../components/DetailPage';
import FileList from '../components/FileList';
import FormModal from '../components/FormModal';
import StatusBadge from '../components/StatusBadge';
import { toast } from '../components/Toast';
import { apiFetch, apiGet, apiPost } from '../utils/dashboardApi';

export default function ClientDetail(){
  const {id}=useParams(); const navigate=useNavigate();
  const [data,setData]=useState(null); const [error,setError]=useState(''); const [editing,setEditing]=useState(false); const [portal,setPortal]=useState(false); const [busy,setBusy]=useState(false);
  const [form,setForm]=useState({});
  const load=useCallback(()=>{setError('');apiGet(`/api/clients/${id}`).then(setData).catch(e=>setError(e.message));},[id]);
  useEffect(load,[load]);
  if(error)return <DashLayout><ErrorDetail message={error} onRetry={load}/></DashLayout>;
  if(!data)return <DashLayout><LoadingDetail/></DashLayout>;
  const {client,projects=[],requests=[],payments=[],communications=[]}=data;
  const openEdit=()=>{setForm({...client});setEditing(true);};
  const save=async e=>{e.preventDefault();setBusy(true);try{await apiFetch(`/api/clients/${id}`,{method:'PATCH',body:form});toast.success('Client updated');setEditing(false);load();}catch(err){toast.error(err.message);}finally{setBusy(false);}};
  const needsSetup=!client.account_setup_completed_at;
  const invite=async()=>{setBusy(true);try{const purpose=needsSetup?'setup-token':'reset-token';const result=await apiPost(`/api/clients/${id}/${purpose}`,{portal_base_url:window.location.origin.replace('dashboard','portal')});setPortal(result); }catch(err){toast.error(err.message);}finally{setBusy(false);}};
  const copyInvite=async()=>{await navigator.clipboard.writeText(portal.url);toast.success('Portal link copied');};
  const archive=async()=>{setBusy(true);try{await apiFetch(`/api/clients/${id}`,{method:'PATCH',body:{status:client.status==='cancelled'?'active':'cancelled'}});toast.success(client.status==='cancelled'?'Client reactivated':'Client archived');load();}catch(err){toast.error(err.message);}finally{setBusy(false);}};
  return <DashLayout><DetailPage eyebrow="Client" title={client.company||client.name} subtitle={`${client.name} · ${client.email}`} meta={<><StatusBadge value={client.status}/><span>{humanize(client.plan)} plan</span><span>{humanize(client.billing)} billing</span><span>{client.active_projects} active projects</span></>} actions={<><button className="btn btn-ghost" onClick={openEdit}>Edit client</button><button className="btn btn-ghost" onClick={()=>setPortal(true)}><KeyRound size={16}/> Portal access</button>{projects[0]&&<button className="btn btn-ghost" onClick={()=>navigate(`/requests?project_id=${projects[0].id}&create=1`)}><Plus size={16}/> New request</button>}<button className="btn btn-primary" onClick={()=>navigate(`/projects?client_id=${client.id}&create=1`)}><FolderPlus size={16}/> New project</button><button className="btn btn-ghost" disabled={busy} onClick={archive}><Archive size={16}/> {client.status==='cancelled'?'Reactivate':'Archive'}</button></>}>
    <div className="detail-grid detail-grid-two">
      <DetailSection title="Account overview"><dl className="definition-grid"><div><dt>Primary contact</dt><dd>{client.name}</dd></div><div><dt>Phone</dt><dd>{client.phone||'Not set'}</dd></div><div><dt>Slot capacity</dt><dd>{client.plan==='enterprise'?3:client.plan==='business'?2:1}</dd></div><div><dt>Next payment</dt><dd>{formatDate(client.next_payment_due)}</dd></div><div><dt>Outstanding</dt><dd>${Number(client.outstanding_amount||0).toLocaleString()}</dd></div><div><dt>White label</dt><dd>{client.whitelabel?'Enabled':'Not enabled'}</dd></div></dl></DetailSection>
      <DetailSection title="Recent communication" description="Latest client portal messages.">{communications.length?<div className="simple-list">{communications.slice(0,5).map(m=><div key={m.id}><strong>{m.sender==='client'?client.name:'Clockwrk'}</strong><p>{m.content}</p><small>{formatDate(m.created_at)}</small></div>)}</div>:<p className="empty-copy">No messages yet.</p>}</DetailSection>
    </div>
    <DetailSection title="Projects" action={<button className="text-action" onClick={()=>navigate(`/projects?client_id=${client.id}&create=1`)}><Plus size={15}/> New project</button>}>{projects.length?<div className="record-list">{projects.map(p=><button key={p.id} onClick={()=>navigate(`/projects/${p.id}`)}><span><strong>{p.name}</strong><small>{humanize(p.type)} · {p.active_requests} active requests</small></span><StatusBadge value={p.status}/></button>)}</div>:<p className="empty-copy">No projects yet.</p>}</DetailSection>
    <DetailSection title="Requests">{requests.length?<div className="record-list">{requests.slice(0,12).map(r=><button key={r.id} onClick={()=>navigate(`/requests/${r.id}`)}><span><strong>{r.title}</strong><small>{r.project_name||'No project'} · due {formatDate(r.due_date)}</small></span><StatusBadge value={r.status}/></button>)}</div>:<p className="empty-copy">No requests yet.</p>}</DetailSection>
    <div className="detail-grid detail-grid-two"><DetailSection title="Billing history">{payments.length?<div className="simple-list">{payments.slice(0,8).map(p=><div key={p.id}><strong>${Number(p.amount).toLocaleString()}</strong><p>{p.payment_ref||'No transfer reference'}</p><StatusBadge value={p.status}/></div>)}</div>:<p className="empty-copy">No payments recorded.</p>}</DetailSection><DetailSection title="Files"><FileList entityType="client" entityId={client.id} canManage/></DetailSection></div>
    <FormModal open={editing} title="Edit client" subtitle="Update the account details used across the dashboard and portal." onClose={()=>setEditing(false)} onSubmit={save} actions={<><button type="button" className="btn btn-ghost" onClick={()=>setEditing(false)}>Cancel</button><button className="btn btn-primary" disabled={busy}>{busy?'Saving...':'Save client'}</button></>}><div className="form-row"><label className="form-field">Company<input className="dash-input" value={form.company||''} onChange={e=>setForm({...form,company:e.target.value})}/></label><label className="form-field">Contact name<input className="dash-input" value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></label></div><div className="form-row"><label className="form-field">Email<input className="dash-input" type="email" value={form.email||''} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="form-field">Phone<input className="dash-input" value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})}/></label></div><label className="form-field">Notes<textarea className="dash-input" rows="4" value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></label></FormModal>
    <FormModal open={Boolean(portal)} title={needsSetup?'Client setup':'Password reset'} subtitle={needsSetup?'Create a one-time /setup link so the client can confirm their profile, add teammates, and choose a password.':'Create a one-time /reset-password link for this established account.'} onClose={()=>setPortal(false)} onSubmit={e=>e.preventDefault()} actions={portal?.url?<><button type="button" className="btn btn-ghost" onClick={()=>setPortal(false)}>Done</button><button type="button" className="btn btn-primary" onClick={copyInvite}><Copy size={16}/> Copy link</button></>:<><button type="button" className="btn btn-ghost" onClick={()=>setPortal(false)}>Cancel</button><button type="button" className="btn btn-primary" disabled={busy} onClick={invite}><KeyRound size={16}/> {needsSetup?'Create setup link':'Create reset link'}</button></>}><div className="secure-link-box">{portal?.url?<><span>{portal.purpose==='setup'?'Expires in 72 hours':`Expires in ${portal.expires_in_minutes} minutes`}</span><code>{portal.url}</code><a href={portal.url} target="_blank" rel="noreferrer">Open link <ExternalLink size={14}/></a></>:<p>{needsSetup?'A new setup link replaces any older setup invitation. Password reset tokens are unaffected.':'A new reset link replaces the previous reset token. The client setup record is unaffected.'}</p>}</div></FormModal>
  </DetailPage></DashLayout>;
}
