import { useEffect, useMemo, useState } from 'react';
import { Download, File, FileArchive, FileCode2, FileImage, FileText, Search, Trash2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import DashLayout from '../components/DashLayout';
import PillSelect from '../components/PillSelect';
import { toast } from '../components/Toast';
import { apiDelete, apiGet } from '../utils/dashboardApi';

const iconFor=file=>{const type=String(file.file_type||file.file_name||'').toLowerCase();if(type.includes('image')||/\.(png|jpg|jpeg|webp|gif|svg)$/.test(type))return FileImage;if(type.includes('zip')||type.includes('archive'))return FileArchive;if(/\.(js|jsx|ts|tsx|css|html|json|sql)$/.test(type))return FileCode2;if(type.includes('pdf')||type.includes('document')||type.includes('text'))return FileText;return File;};
const fmtDate=value=>value?new Date(value).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'-';

export default function Files(){const navigate=useNavigate();const [files,setFiles]=useState([]);const [search,setSearch]=useState('');const [category,setCategory]=useState('all');const [loading,setLoading]=useState(true);const load=()=>{setLoading(true);apiGet('/api/files/records').then(data=>setFiles(data.files||[])).catch(err=>toast.error(err.message)).finally(()=>setLoading(false));};useEffect(load,[]);const filtered=useMemo(()=>files.filter(file=>(category==='all'||file.category===category)&&(!search||[file.file_name,file.client_company,file.project_name,file.request_title].join(' ').toLowerCase().includes(search.toLowerCase()))),[files,search,category]);const remove=async file=>{if(!confirm(`Delete ${file.file_name}?`))return;try{await apiDelete(`/api/files/records/${file.id}`);toast.success('File deleted');load();}catch(err){toast.error(err.message);}};return <DashLayout><div className="files-page launch-list-page"><header className="page-header"><div><span className="page-eyebrow">Shared files</span><h1>Files and deliverables</h1><p>Every file keeps its client, project and request context.</p></div></header><div className="list-toolbar"><label className="search-control"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search files, clients, projects or requests"/></label><PillSelect className="compact-control" value={category} onChange={setCategory} ariaLabel="Filter file type" options={[{value:'all',label:'All file types'},{value:'attachment',label:'Client attachments'},{value:'deliverable',label:'Deliverables'}]}/></div>{loading?<div className="overview-loading">Loading files...</div>:filtered.length?<div className="file-browser-list">{filtered.map(file=>{const Icon=iconFor(file);return <article key={file.id}><span className="file-browser-icon"><Icon size={22}/></span><button className="file-browser-name" onClick={()=>file.request_id?navigate(`/requests/${file.request_id}`):file.project_id?navigate(`/projects/${file.project_id}`):navigate(`/clients/${file.client_id}`)}><strong>{file.file_name}</strong><small>{file.client_company||'No client'} · {file.project_name||'No project'} · {file.request_title||'No request'}</small></button><span className="file-browser-meta"><Status value={file.category}/><small>{file.version||'Latest'} · {fmtDate(file.created_at)}</small></span><a className="icon-action" href={file.file_url} target="_blank" rel="noreferrer" aria-label={`Download ${file.file_name}`}><Download size={17}/></a><button className="icon-action danger" onClick={()=>remove(file)} aria-label={`Delete ${file.file_name}`}><Trash2 size={17}/></button></article>})}</div>:<div className="empty-state"><p>No files match these filters.</p><span>Request attachments and team deliverables will appear here automatically.</span></div>}</div></DashLayout>}
function Status({value}){return <span className="quiet-label">{String(value||'file').replaceAll('_',' ')}</span>}
