import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowUp, Check, FileUp, MessageSquare, Plus, Send, Trash2 } from 'lucide-react';
import { useParams } from 'react-router-dom';
import DashLayout from '../components/DashLayout';
import { DetailPage, DetailSection, ErrorDetail, LoadingDetail, formatDate, humanize } from '../components/DetailPage';
import FormModal from '../components/FormModal';
import PillSelect from '../components/PillSelect';
import StatusBadge from '../components/StatusBadge';
import { toast } from '../components/Toast';
import { apiFetch, apiGet, apiPost } from '../utils/dashboardApi';

const NEXT={queue:{label:'Start work',status:'in_progress'},in_progress:{label:'Send to client review',status:'in_review'},revision:{label:'Send revision to review',status:'in_review'},in_review:{label:'Mark delivered',status:'completed'}};
const newPart=position=>({title:'',description:'',priority:'normal',position,depends_on_position:''});

export default function RequestDetail(){
  const {id}=useParams();const fileRef=useRef();const [data,setData]=useState(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [comment,setComment]=useState('');const [visibility,setVisibility]=useState('internal');const [parts,setParts]=useState([]);const [editing,setEditing]=useState(false);const [form,setForm]=useState({});
  const load=useCallback(()=>{setError('');apiGet(`/api/requests/${id}`).then(result=>{setData(result);setParts(result.parts?.length?result.parts.map(p=>({...p,depends_on_position:p.depends_on_position||''})):[newPart(1),newPart(2)]);}).catch(e=>setError(e.message));},[id]);useEffect(load,[load]);
  if(error)return <DashLayout><ErrorDetail message={error} onRetry={load}/></DashLayout>;if(!data)return <DashLayout><LoadingDetail/></DashLayout>;
  const {request,comments=[],files=[],activity=[],children=[],team=[]}=data;const next=NEXT[request.status];
  const patch=async body=>{setBusy(true);try{await apiFetch(`/api/requests/${id}`,{method:'PATCH',body});toast.success('Request updated');load();}catch(err){toast.error(err.message);}finally{setBusy(false);}};
  const addComment=async e=>{e.preventDefault();if(!comment.trim())return;setBusy(true);try{await apiPost(`/api/requests/${id}/comments`,{comment,visibility});setComment('');toast.success(visibility==='client'?'Reply sent to client':'Internal note added');load();}catch(err){toast.error(err.message);}finally{setBusy(false);}};
  const upload=async event=>{const file=event.target.files?.[0];if(!file)return;const body=new FormData();body.append('file',file);body.append('request_id',id);body.append('category','deliverable');setBusy(true);try{await apiFetch('/api/files/request-upload',{method:'POST',body});toast.success('Deliverable uploaded');load();}catch(err){toast.error(err.message);}finally{event.target.value='';setBusy(false);}};
  const startBreakdown=async()=>{setBusy(true);try{await apiPost(`/api/requests/${id}/scope/start`);toast.success('Scope review started');load();}catch(err){toast.error(err.message);}finally{setBusy(false);}};
  const saveDraft=async()=>{setBusy(true);try{await apiFetch(`/api/requests/${id}/breakdown`,{method:'PUT',body:{parts,send_to_client:false}});toast.success('Breakdown draft saved');load();}catch(err){toast.error(err.message);}finally{setBusy(false);}};
  const sendBreakdown=async()=>{setBusy(true);try{if(request.scope_status!=='reviewing')await apiFetch(`/api/requests/${id}/breakdown`,{method:'PUT',body:{parts,send_to_client:false}});await apiPost(`/api/requests/${id}/breakdown/send`);toast.success('Breakdown sent to client');load();}catch(err){toast.error(err.message);}finally{setBusy(false);}};
  const move=(index,delta)=>{const target=index+delta;if(target<0||target>=parts.length)return;const next=[...parts];[next[index],next[target]]=[next[target],next[index]];setParts(next.map((p,i)=>({...p,position:i+1,depends_on_position:Number(p.depends_on_position)>i?'':p.depends_on_position})));};
  const openEdit=()=>{setForm({...request});setEditing(true);};const saveEdit=async e=>{e.preventDefault();await patch({title:form.title,description:form.description,type:form.type,priority:form.priority,due_date:form.due_date||null,estimated_hours:form.estimated_hours||null});setEditing(false);};
  return <DashLayout><DetailPage eyebrow={request.request_kind==='parent'?'Request group':'Request'} title={request.title} subtitle={`${request.client_company||request.client_name} · ${request.project_name}`} meta={<><StatusBadge value={request.status}/><StatusBadge value={request.priority}/><span>{humanize(request.type)}</span>{request.queue_position&&<span>Queue {Math.round(Number(request.queue_position)/1024)}</span>}<span>Due {formatDate(request.due_date)}</span></>} actions={<><button className="btn btn-ghost" onClick={openEdit}>Edit request</button><label className="btn btn-ghost"><FileUp size={16}/> Upload deliverable<input ref={fileRef} hidden type="file" onChange={upload}/></label>{next&&request.request_kind!=='parent'&&<button className="btn btn-primary" disabled={busy} onClick={()=>patch({status:next.status})}>{next.label} <Check size={16}/></button>}</>}>
    {request.depends_on_request_id&&request.dependency_status!=='completed'&&<div className="operational-alert warning"><strong>Blocked by {request.dependency_title}</strong><span>This request cannot start until its dependency is delivered.</span></div>}
    {request.status==='revision'&&<div className="operational-alert danger"><strong>Client revision requested</strong><span>{request.revision_notes||'Open the discussion below for the client’s exact notes.'}</span></div>}
    <div className="detail-grid request-overview-grid"><DetailSection title="Client brief" description="The original source of truth from the client."><p className="long-copy">{request.description||'No written brief was supplied.'}</p>{files.filter(f=>f.category==='attachment').length>0&&<div className="attachment-strip">{files.filter(f=>f.category==='attachment').map(f=><a key={f.id} href={f.file_url} target="_blank" rel="noreferrer">{f.file_name}</a>)}</div>}</DetailSection><DetailSection title="Production details"><label className="form-field">Assigned to<PillSelect value={String(request.assigned_to||'')} onChange={assigned_to=>patch({assigned_to:assigned_to||null})} ariaLabel="Assign request" options={[{value:'',label:'Unassigned'},...team.map(member=>({value:String(member.id),label:`${member.name} · ${humanize(member.role)}`}))]}/></label><dl className="definition-grid"><div><dt>Estimate</dt><dd>{Number(request.estimated_hours||0)} hours</dd></div><div><dt>Progress</dt><dd>{Number(request.completion_percent||0)}%</dd></div><div><dt>Approval</dt><dd>{humanize(request.approval_status)}</dd></div><div><dt>Created</dt><dd>{formatDate(request.created_at)}</dd></div></dl></DetailSection></div>
    {(request.request_kind==='parent'||(request.status==='queue'&&request.request_kind==='normal'))&&<DetailSection title="Breakdown and dependencies" description="Organize an oversized request into a simple ordered checklist. Save privately, then send it to the client when ready." action={request.request_kind==='normal'?<button className="btn btn-ghost" disabled={busy} onClick={startBreakdown}>Break down request</button>:null}>{request.request_kind==='normal'?<p className="empty-copy">This is currently a normal queued request.</p>:<><div className="breakdown-editor">{parts.map((part,index)=><div className="breakdown-row" key={part.id||index}><span className="part-number">{index+1}</span><div><input className="dash-input" placeholder="Part title" value={part.title} onChange={e=>setParts(parts.map((p,i)=>i===index?{...p,title:e.target.value}:p))}/><textarea className="dash-input" rows="2" placeholder="What this part includes" value={part.description||''} onChange={e=>setParts(parts.map((p,i)=>i===index?{...p,description:e.target.value}:p))}/><PillSelect value={String(part.depends_on_position||'')} onChange={depends_on_position=>setParts(parts.map((p,i)=>i===index?{...p,depends_on_position}:p))} ariaLabel={`Part ${index+1} dependency`} options={[{value:'',label:'No dependency'},...parts.slice(0,index).map((p,i)=>({value:String(i+1),label:`After part ${i+1}: ${p.title||'Untitled'}`}))]}/></div><div className="breakdown-controls"><button className="icon-action" onClick={()=>move(index,-1)} disabled={!index}><ArrowUp size={16}/></button><button className="icon-action" onClick={()=>move(index,1)} disabled={index===parts.length-1}><ArrowDown size={16}/></button><button className="icon-action danger" onClick={()=>setParts(parts.filter((_,i)=>i!==index))} disabled={parts.length<=2}><Trash2 size={16}/></button></div></div>)}</div><button className="text-action" onClick={()=>setParts([...parts,newPart(parts.length+1)])}><Plus size={15}/> Add part</button><div className="section-actions"><button className="btn btn-ghost" disabled={busy} onClick={saveDraft}>Save draft</button><button className="btn btn-primary" disabled={busy||parts.some(p=>!p.title.trim())} onClick={sendBreakdown}><Send size={16}/> Send to client</button></div>{request.scope_status==='proposed'&&<p className="inline-notice">Awaiting client approval. Editing is locked in the portal until they approve or ask for changes.</p>}</>}</DetailSection>}
    {children.length>0&&<DetailSection title="Approved request parts"><div className="record-list">{children.map(c=><button key={c.id} onClick={()=>location.assign(`/requests/${c.id}`)}><span><strong>{c.part_number}. {c.title}</strong><small>{c.dependency_title?`Starts after ${c.dependency_title}`:'No dependency'}</small></span><StatusBadge value={c.status}/></button>)}</div></DetailSection>}
    <div className="detail-grid request-work-grid"><div><DetailSection title="Files and deliverables" action={<label className="text-action"><FileUp size={15}/> Upload<input hidden type="file" onChange={upload}/></label>}>{files.filter(f=>f.category!=='attachment').length?<div className="record-file-list">{files.filter(f=>f.category!=='attachment').map(f=><a className="record-file-row" key={f.id} href={f.file_url} target="_blank" rel="noreferrer"><span><strong>{f.file_name}</strong><small>{f.version||'Latest'} · {formatDate(f.created_at)}</small></span></a>)}</div>:<p className="empty-copy">No deliverables uploaded yet.</p>}</DetailSection><DetailSection title="Discussion" description="Client-visible replies appear in the portal. Internal notes stay in the dashboard.">{comments.length?<div className="comment-list">{comments.map(c=><article className={c.author_type==='client'?'client-comment':''} key={c.id}><header><strong>{c.author_name||'Clockwrk'}</strong><StatusBadge value={c.visibility}/><small>{formatDate(c.created_at)}</small></header><p>{c.comment}</p></article>)}</div>:<p className="empty-copy">No comments yet.</p>}<form className="comment-composer" onSubmit={addComment}><textarea className="dash-input" rows="3" placeholder="Write a clear update or internal note" value={comment} onChange={e=>setComment(e.target.value)}/><div><PillSelect value={visibility} onChange={setVisibility} ariaLabel="Comment visibility" options={[{value:'internal',label:'Internal note'},{value:'client',label:'Reply to client'}]}/><button className="btn btn-primary" disabled={busy||!comment.trim()}><MessageSquare size={16}/> Add comment</button></div></form></DetailSection></div><DetailSection title="Activity"><div className="activity-list">{activity.map(a=><div key={a.id}><i/><span><strong>{a.label}</strong><small>{formatDate(a.created_at)}</small></span></div>)}</div></DetailSection></div>
    <FormModal open={editing} title="Edit request" onClose={()=>setEditing(false)} onSubmit={saveEdit} actions={<><button type="button" className="btn btn-ghost" onClick={()=>setEditing(false)}>Cancel</button><button className="btn btn-primary" disabled={busy}>Save request</button></>}><label className="form-field">Title<input className="dash-input" value={form.title||''} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="form-field">Brief<textarea className="dash-input" rows="6" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="form-row"><label className="form-field">Priority<PillSelect value={form.priority||'normal'} onChange={priority=>setForm({...form,priority})} ariaLabel="Request priority" options={['low','normal','high','urgent']}/></label><label className="form-field">Due date<input className="dash-input" type="date" value={String(form.due_date||'').slice(0,10)} onChange={e=>setForm({...form,due_date:e.target.value})}/></label></div></FormModal>
  </DetailPage></DashLayout>;
}
