import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Icon from '../Icon';
import { Action } from '../Primitives';

export default function NewProject() {
  const navigate = useNavigate();
  const [name, setName] = useState('');
  const [type, setType] = useState('Software');
  const [submitted, setSubmitted] = useState(false);
  if (submitted) return <section className="v3-composer-success"><i><Icon name="projects" size={30} /></i><span>Project workspace created</span><h1>{name}</h1><p>Your team can now add requests, references, collaborators, and delivery milestones.</p><Action onClick={() => navigate('/projects')}>Open projects</Action></section>;
  return <div className="v3-project-builder"><header><button onClick={() => navigate('/projects')}><Icon name="back" /></button><span>New project</span><strong>Workspace setup</strong></header><main><aside><span>One clear source of truth</span><h1>Build the project around its outcome.</h1><p>This context follows every request, message, file, and team member added later.</p><ol><li className="is-active"><i>1</i>Identity</li><li><i>2</i>Direction</li><li><i>3</i>Delivery</li></ol></aside><form onSubmit={(event) => { event.preventDefault(); if (name.trim()) setSubmitted(true); }}><section><span>01 · Identity</span><h2>Name the workspace</h2><label><span>Project name</span><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Platform launch" /></label><div className="v3-type-choice">{['Software','Website','Brand','Campaign','Internal'].map((item) => <button type="button" key={item} className={type === item ? 'is-active' : ''} onClick={() => setType(item)}>{item}</button>)}</div></section><section><span>02 · Direction</span><h2>Give the team the why</h2><label><span>Primary goal</span><textarea placeholder="What must this project achieve?" /></label><div className="v3-field-pair"><label><span>Audience</span><input placeholder="Who is it for?" /></label><label><span>Success measure</span><input placeholder="How will you know it worked?" /></label></div></section><section><span>03 · Delivery</span><h2>Set the working boundaries</h2><div className="v3-field-pair"><label><span>Target date</span><input type="date" /></label><label><span>Budget context</span><select defaultValue="Retainer"><option>Retainer</option><option>One-time build</option><option>Not decided</option></select></label></div><label className="v3-upload"><Icon name="attach" /><span><strong>Add source material</strong><small>Briefs, brand files, research, repositories, or references</small></span></label></section><footer><span>{name ? `${name} · ${type}` : 'Add a project name to continue'}</span><Action type="submit" disabled={!name.trim()} icon="check">Create project</Action></footer></form></main></div>;
}
