import { useState } from 'react';
import { domainsSeed, reportsSeed, securitySeed } from '../../mocks';
import { store, useStore } from '../../store';
import Icon from '../Icon';
import { Action, PageIntro, Status } from '../Primitives';

export default function Site() {
  const { hosting, domains, mailboxes, securityMonitors, reports } = useStore();
  const [tab, setTab] = useState('hosting');
  const tabs = [['hosting', 'Hosting'], ['domains', 'Domains'], ['email', 'Email'], ['security', 'Security'], ['reports', 'Reports']];
  return <div className="v3-site-page"><PageIntro index="Managed infrastructure" title="My site" copy="The operational layer behind your live products, maintained by the same team that built them." action={<Action icon="external">Open live site</Action>} />
    <section className="v3-site-health v3-enter"><div><i /><span><strong>Everything is healthy</strong><small>Checked 2 minutes ago</small></span></div><p><strong>99.99%</strong> uptime this month</p><p><strong>4h</strong> since last backup</p><p><strong>0</strong> active security alerts</p></section>
    <nav className="v3-site-tabs">{tabs.map(([id, label]) => <button key={id} className={tab === id ? 'is-active' : ''} onClick={() => setTab(id)}>{label}</button>)}</nav>
    {tab === 'hosting' && <section className="v3-ops-sheet v3-enter"><header><div><span>Production hosting</span><h2>{hosting.accounts[0]?.domain || 'm94group.com'}</h2></div><Status status="active">Operational</Status></header><div className="v3-ops-metrics"><span><small>Uptime</small><strong>{hosting.accounts[0]?.uptime || '99.99'}%</strong></span><span><small>Region</small><strong>Singapore</strong></span><span><small>Runtime</small><strong>Edge + Node</strong></span><span><small>SSL</small><strong>Valid</strong></span></div><div className="v3-backup-line"><span><Icon name="clock" /><strong>Automatic backups</strong><small>Daily · 30-day retention</small></span><button onClick={store.runBackup}>Run backup now</button></div></section>}
    {tab === 'domains' && <section className="v3-ops-sheet v3-enter"><header><div><span>Domain portfolio</span><h2>{domains.length} managed domains</h2></div></header><div className="v3-domain-list">{(domains.length ? domains : domainsSeed).map((domain) => <div key={domain.id}><span><i />{domain.name}</span><small>Renews {domain.renewalAt}</small><label><input type="checkbox" checked={domain.autoRenew} onChange={(event) => store.setDomainAutoRenew(domain.id, event.target.checked)} />Auto-renew</label><Icon name="arrow" size={15} /></div>)}</div></section>}
    {tab === 'email' && <section className="v3-ops-sheet v3-enter"><header><div><span>Business email</span><h2>{mailboxes.length} active mailboxes</h2></div></header><div className="v3-domain-list">{mailboxes.map((box) => <div key={box.id}><span><i />{box.email}</span><small>{box.plan} plan</small><Status status="active">Active</Status><Icon name="arrow" size={15} /></div>)}</div></section>}
    {tab === 'security' && <section className="v3-ops-sheet v3-enter"><header><div><span>Security posture</span><h2>All monitors passing</h2></div><strong className="v3-security-score">A</strong></header><div className="v3-domain-list">{(securityMonitors.length ? securityMonitors : securitySeed).map((monitor) => <div key={monitor.id}><span><i className={monitor.on ? 'is-on' : ''} />{monitor.name}</span><small>{monitor.lastRun || 'Checked today'}</small><label><input type="checkbox" checked={monitor.on} onChange={(event) => store.toggleMonitor(monitor.id, event.target.checked)} />Enabled</label></div>)}</div></section>}
    {tab === 'reports' && <section className="v3-ops-sheet v3-enter"><header><div><span>Reports</span><h2>Health and performance records</h2></div></header><div className="v3-report-grid">{(reports.length ? reports : reportsSeed).map((report) => <button key={report.id}><span>{report.type || 'Monthly'}</span><h3>{report.title}</h3><small>{report.createdAt || 'Jul 1, 2026'}</small><Icon name="download" /></button>)}</div></section>}
  </div>;
}
